services:
 - docker
before_install:
  - docker run --rm -i lukasmartinelli/hadolint hadolint --ignore DL4000 --ignore DL3003 - < Dockerfile
install:
  - docker build -t grafana-graphite .
  - docker run -d -p 127.0.0.1:80:80 -p 127.0.0.1:81:81 -p 127.0.0.1:2003:2003 --name grafana-graphite grafana-graphite
script:
  - docker ps | grep -q grafana-graphite
