version: '2.1'
services:
  grafana_graphite:
    image: stats-alpine #ymajik/docker-grafana-graphite:develop-alpine
    ports:
      - '80:80'
      - '81:81'
      - '2003:2003'
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./data/grafana:/opt/grafana/data
      - ./log/graphite:/opt/graphite/storage/log
      - ./graphite:/opt/graphite/conf
