version: '2'
services:
  grafana_graphite:
    build: .
    image: ymajik/grafana_graphite
    container_name: ymajik-grafana-dashboard
    ports:
      - '80:80'
      - '81:81'
      - '8125:8125/udp'
      - '8126:8126'
      - '2003:2003'
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./data/grafana:/opt/grafana/data
      - ./log/graphite:/opt/graphite/storage/log
      - ./graphite:/opt/graphite/conf
